# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# 2020年11月30日16:53:51 https://github.com/ddgksf2013/TaskAction/blob/master/youth/Task/youth.js

name: 头条&火山&葱花

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【今日头条极速版】'
        run: |
          node ./workflow/jrtt.js
        env:
          TZ: Asia/shanghai
          YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
          YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
          YOUTH_REDBODY: ${{ secrets.YOUTH_REDBODY }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
          YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}

      - name: '运行 【火山小视频】'
        run: |
          node ./workflow/hotsoon.js
        env:
          TZ: Asia/shanghai
          HOTSOONSIGNHEADER: ${{ secrets. HOTSOONSIGNHEADER }}
          HOTSOONSIGNKEY: ${{ secrets. HOTSOONSIGNKEY }}
          HOTSOONADHEADER: ${{ secrets. HOTSOONADHEADER }}
          HOTSOONADKEY: ${{ secrets. HOTSOONADKEY }}
          HOTSOONREADHEADER: ${{ secrets. HOTSOONREADHEADER }}
          HOTSOONREADKEY: ${{ secrets. HOTSOONREADKEY }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}

      - name: '运行 【葱花视频】'
        run: |
          node ./workflow/chonghua.js
        env:
          TZ: Asia/shanghai
          PUSH_KEY: ${{ secrets.PUSH_KEY }}